
# some defaults
prefix	?= /usr
CC	= gcc
CFLAGS	= -Wall -Werror -O2 -ggdb
CPPFLAGS = -I../../lib/include

SPU_CC	= spu-gcc

# libspe1 helpers
LIBSPE1_CFLAGS = -I$(prefix)/include
LIBSPE1_LDFLAGS  = -L$(prefix)/lib -lspe

# libspe2 helpers
LIBSPE2_CFLAGS = -I$(prefix)/include
LIBSPE2_LDFLAGS  = -L$(prefix)/lib -lspe2

obj =

include Makefile

all: $(obj)

clean:
	rm -f $(obj)
	rm -f *.o

# helper rules for embedded spe binaries
%_embed.o: %
	embedspu $^_app $^ $@
