
# some defaults
prefix	?= /usr
CC	= gcc
CFLAGS	= -Wall -Werror -O2 -ggdb
CPPFLAGS = -I../../lib/include

SPU_CC	= spu-gcc

# libspe1 helpers
LIBSPE1_CFLAGS = -I$(prefix)/include
LIBSPE1_LDFLAGS  = -L$(prefix)/lib -lspe

# libspe2 helpers
LIBSPE2_CFLAGS = -I$(prefix)/include
LIBSPE2_LDFLAGS  = -L$(prefix)/lib -lspe2

obj =
clean =

include Makefile

all: $(obj)

clean:
	rm -f $(obj) $(clean)
	rm -f *.o

# Rules for building 64 bit binaries
%-64: CFLAGS += -m64

%-64: %.c
	$(COMPILE.c) -o $@ $^

# helper rules for embedded spe binaries
%.spe-embed.o: %.spe
	embedspu $*_spe_app $^ $@

%.spe: CC=$(SPU_CC)
%.spe: LDFLAGS=

%.spe.o: CC=$(SPU_CC)
%.spe.o: LDFLAGS=

%.spe: %.spe.c
	$(LINK.c) $^ $(LOADLIBES) $(LDLIBS) -o $@

%.spe:
	$(LINK.o) $^ -o $@

%.spe.o: %.spe.c
	$(COMPILE.c) -o $@ $^

%.spe.o: %.spe.S
	$(COMPILE.S) -o $@ $^
