# Testsuite for the Linux SPU filesystem
#
# Copyright (C) IBM Corporation, 2007
#
# Author: Jeremy Kerr <jk@ozlabs.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# some defaults
prefix	?= /usr
CC	= gcc
CFLAGS	= -Wall -Werror -O2 -ggdb
CPPFLAGS = -I../../lib/include

SPU_CC	= spu-gcc

# libspe1 helpers
LIBSPE1_CFLAGS = -I$(prefix)/include
LIBSPE1_LDFLAGS  = -L$(prefix)/lib -lspe

# libspe2 helpers
LIBSPE2_CFLAGS = -I$(prefix)/include
LIBSPE2_LDFLAGS  = -L$(prefix)/lib -lspe2

obj =
clean =

include Makefile

all: $(obj)

clean:
	rm -f $(obj) $(clean)
	rm -f *.o

# Rules for building 64 bit binaries
%-64: CFLAGS += -m64

%-64: %.c
	$(COMPILE.c) -o $@ $^

# helper rules for embedded spe binaries
%.spe-embed.o: %.spe
	embedspu $*_spe_app $^ $@

%.spe: CC=$(SPU_CC)
%.spe: LDFLAGS=

%.spe.o: CC=$(SPU_CC)
%.spe.o: LDFLAGS=

%.spe: %.spe.c
	$(LINK.c) $^ $(LOADLIBES) $(LDLIBS) -o $@

%.spe:
	$(LINK.o) $^ -o $@

%.spe.o: %.spe.c
	$(COMPILE.c) -o $@ $^

%.spe.o: %.spe.S
	$(COMPILE.S) -o $@ $^
