
obj += 01-no-destroy 02-internal-reference 03-external-reference

01-no-destroy: 01-no-destroy.o gang-presence.o
02-internal-reference: 02-internal-reference.o gang-presence.o
03-external-reference: 03-external-reference.o gang-presence.o
